name: orient_benin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # L'outil d'icônes, placé ici sans créer de doublon de dev_dependencies
  flutter_launcher_icons: ^0.14.4

# Cette section unique contrôle les ressources globales de votre application
flutter:
  uses-material-design: true

  # Déclaration de TOUS vos fichiers du dossier images pour qu'ils soient reconnus
  assets:
    - assets/images/logo.png
    - assets/images/logos.png

# Configuration pour l'icône officielle (qui utilise le fichier avec le s)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos.png"
  min_sdk_android: 21
